# Generated by Django 3.1.6 on 2021-03-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=500)),
                ('message', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
